#This tells Docker to use the OpenJDK 17 base image from Docker Hub

from openjdk:17

# This copies your Spring Boot JAR file
#(from your local target/ directory after build with Maven) into the Docker image.
#The source is:
    #target/Appoiment-System-0.0.1-SNAPSHOT.jar → the JAR generated by mvn clean package or mvn clean install -DskipTests

#The destination is:
    # appoinment.jar is put inside the container.

add target/Appoiment-System-0.0.1-SNAPSHOT.jar appoinment.jar
# we manually run the jar file like this => java -jar Jar_file_name.jar
#so Incase the automatically run our application by docker  using docker run
# the docker takes this command
entrypoint [ "java","-jar","appoinment.jar"]
#In Docker, EXPOSE only tells Docker that the container listens on a given port internally
expose 8080